#!/bin/bash

## Install all dependencies for emacs to run at full capacity

EMACS_PKG=emacs-nativecomp

if ! command -v emacs > /dev/null; then
    if sudo pacman -S "$EMACS_PKG"; then
        echo "Could not install emacs. Exiting"
        exit 1
    fi
fi

if command -v yay > /dev/null; then
    emacs -batch -l init.el -f nd/install-arch-dependencies
else
    echo "Yay not installed. Exiting"
    exit 1
fi
